// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYo6jEmioAED9am6g55pVXkKUiUIQkDJ8',
    appId: '1:189724068141:web:0f6daa0df1b28ed80f2ba4',
    messagingSenderId: '189724068141',
    projectId: 'crawlstorage',
    authDomain: 'crawlstorage.firebaseapp.com',
    databaseURL: 'https://crawlstorage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crawlstorage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-Rg-EwSqlPWEEs1aYxj7RZfJAO_Zw98',
    appId: '1:189724068141:android:802516ed7e68b6990f2ba4',
    messagingSenderId: '189724068141',
    projectId: 'crawlstorage',
    databaseURL: 'https://crawlstorage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crawlstorage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDnpHeNOoDKirOHogYJdgdGRIYqL48hw',
    appId: '1:189724068141:ios:0776def6e2a0fbc80f2ba4',
    messagingSenderId: '189724068141',
    projectId: 'crawlstorage',
    databaseURL: 'https://crawlstorage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crawlstorage.appspot.com',
    androidClientId: '189724068141-0ae6s6s04ae231322nido58mc4jqj8pb.apps.googleusercontent.com',
    iosClientId: '189724068141-phcj51makhsnrl9b2b9e39vokdt6qbei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDestroyer',
  );
}
